### ISSUE TITLE
Typemill Roadmap

### ISSUE THREAD

**Issue by trendschau** [typemill/typemill#35]
For full changelog please visit the [Typemill Release Infos](https://typemill.net/news)

**1.0.X Series: The Birth**
- [x] Version 1.0.0: Introducing TYPEMILL
- [x] Version 1.0.1: Added a google sitemap
- [x] Version 1.0.5: Added a table of contents tag (TOC)

**1.1.X Series: Plugin System and Author Panel**
- [x] Version 1.1.0: Introducing a plugin system
- [x] Version 1.1.3: Introducing an author panel for configurations
- [x] Version 1.1.5: Added math support (mathjax/katex)

**1.2.X Series: Visual Markdown Editor**
- [x] Version 1.2.0: Basic content editor
- [x] Version 1.2.2: Draft management for pages
- [x] Version 1.2.3: Re-order content pages with drag&drop
- [x] Version 1.2.5: Create new pages
- [x] Version 1.2.6: First visual editor version
- [x] Version 1.2.7: Reorder content blocks
- [x] Version 1.2.8: Image component
- [x] Version 1.2.9: Videos and public forms
- [x] Version 1.2.10: New editor components
- [x] Version 1.2.11: Table component
- [x] Version 1.2.12: Content blocks everywhere
- [x] Version 1.2.13: Definition lists and horizontal lines
- [x] Version 1.2.14: Interactive table of contents
- [x] Version 1.2.15: Math refactored
- [x] Version 1.2.16: Footnotes and search plugin
- [x] Version 1.2.17: Inline Formats
- [x] Version 1.2.18: Discard changes and more inline formats
- [x] Version 1.2.19: Modularize the visual editor

**1.3.X Series: Meta-Information**
- [x] Version 1.3.0: Meta-YAML for files and folders (see [Milestones](/typemill/typemill/milestone/1))
- [x] Version 1.3.1: Additional Standard Metas and Internationalization (see [Milestones](/typemill/typemill/milestone/3))
- [x] Version 1.3.2: Rename and hide navigation (see [Milestones](/typemill/typemill/milestone/5))
- [x] Version 1.3.3: Pages and Posts (see [Milestones](/typemill/typemill/milestone/4))
- [x] Version 1.3.4: Improved Media Management (see [Milestones](/typemill/typemill/milestone/6))
- [x] Version 1.3.5: Consolidation (bugfixing)
- [x] Version 1.3.6: Image Field
- [x] Version 1.3.7: Image Manipulation
- [x] Version 1.3.8: Roles and rights concept (ACL)

**1.4.X Series: ebook publishing**
- [x] Version 1.4.0: Generate eBooks (PDF) with the eBook-Plugin
- [x] Version 1.4.1: New fieldtype Customfields (similar to WordPress)
- [x] Version 1.4.2: Small improvements and eBook plugin 1.1.0 (generate eBooks in tabs of pages).
- [x] Version 1.4.3: Improved user rights and user roles and a register plugin
- [x] Version 1.4.4.: Access Control for individual pages (create membership content).
- [ ] Version 1.4.5.: Optimized user management for more than 10 users.
- [ ] Version 1.4.6.: Subscription Plugin.

**Comment by laurensiusadi** [comment]
I think this issue needs an update
Also this page is 404: https://typemill.net/info/release-notes

**Comment by trendschau** [comment]
Yes, thank you, roughly updated

**Comment by trendschau** [comment]
sorry, i don't have the time to update this every time, so I close it. Follow the news on typemill for regular updates: https://typemill.net/news
