### ISSUE TITLE
Deployment Checklist

### ISSUE THREAD

**Issue by trendschau** [typemill/typemill#67]
This is the actual process for each live deployment. Works for now locally, web-based automation with jenkins feels like an overhead right now...

## Prepare

- [ ] update git ignore
- [ ] update news on setup startscreen
- [ ] git commit
- [ ] merge version branch with master
- [ ] update dependencies with composer
- [ ] update version in system/settings.php
- [ ] add parameter to js- and css-files (automatize with url-fingerprinting)
- [ ] write cypress tests

## Build

Simple php script that creates a zip, adds only necessary files (no test or dev files), moves zip to test-folder, deletes old version from test folder, unzipes files to test folder and moves zip back to development folder into the zip-archive-folder.

- [ ] update build.php script locally
- [ ] run build.php script locally

## Test

- [ ] run cypress tests
- [ ] test manually

## Deploy Live

- [ ] update release note in documentation on github
- [ ] update documentation on github
- [ ] pull github documentation to local
- [ ] upload changes to typemill live page
- [ ] deploy code from test-folder to live
- [ ] upload new zip-file
- [ ] update startpage (link on cover and footer)
- [ ] delete old zip-file
- [ ] upload updated themes and plugins if needed

## Push to GitHub

- [ ] update git ignore
- [ ] commit with "Version x.x.x: Description"
- [ ] Push origin master
- [ ] Check on GitHub
- [ ] Clone locally and test again

## Next Release

- [ ] delete old release branch locally
- [ ] create new release branch locally
